# Stage 1: Development for React frontend with HMR
FROM oven/bun:alpine AS frontend-dev

WORKDIR /app/frontend

COPY frontend/bun.lockb frontend/package.json ./
RUN bun install

COPY frontend/ .
RUN bun run build

# Stage 2: Bun backend for development
FROM oven/bun:alpine AS backend

WORKDIR /app

COPY bun.lockb package.json ./
RUN bun install

COPY . .

EXPOSE 8080

CMD ["bun", "run", "start"]
