# version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules  # Avoid overwriting node_modules
    environment:
      - NODE_ENV=development
    networks:
      - expense-tracker

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://server:8080
    networks:
      - expense-tracker

networks:
  expense-tracker:
